import type { Metadata } from "next";
import { headers } from 'next/headers';
import "./globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "./shared-components/header";
import Footer from "./shared-components/footer";
import HeaderMobile from "./shared-components/header-mobile";
import FooterMobile from "./shared-components/footer-mobile";

//const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const userAgent = headersList.get('user-agent') || '';
  const isMobile = /Mobi|Android/i.test(userAgent);
  return (
    <html lang="en">
      <body className={isMobile ? 'mobile' : 'desktop'}>
     {isMobile  ? <HeaderMobile /> :   <Header />} 
        {children}
        {isMobile  ? <FooterMobile />  :   <Footer />} 
        </body>
    </html>
  );
}
